#!/bin/bash
cd /home/ec2-user/news-search-app

# Setting up enviroment variables
export NODE_ENV=development
export PORT=80
export AWS_REGION=ap-southeast-1

# Creating DB
node db/migration.js

# Strat the app using forever
forever start app.js
