#!/bin/bash
cd /home/ec2-user/node-website


export NODE_ENV=production
export PORT=80
export AWS_REGION=ap-southeast-1

node db/models/business.js
node db/models/sessions.js
node db/models/users.js
node db/models/socialMedia.js
node db/models/keyword.js


forever start app.js
